Program("tester",
        ["main.cpp",
         "BencodeDecoder.cpp",
         "Tokenizer.cpp",
         "PrettyPrinter.cpp",
         "TestBencodeDecoder.cpp",
         "TestTokenizer.cpp",
         "TestValueTypes.cpp"],
        LIBS = ["cppunit", "libboost_regex-mt"],
        CPPPATH = ".",
        CXXFLAGS = "-g -Wall -Werror")
