Program("tester",
        ["main.cpp",
         "Bencode.cpp",
         "BencodeDecoder.cpp",
         "Tokenizer.cpp",
         "TestBencode.cpp",
         "TestBencodeDecoder.cpp",
         "TestTokenizer.cpp",
         "TestValueTypes.cpp"],
        LIBS = ["cppunit", "libboost_regex-mt"],
        CXXFLAGS = "-g -Wall -Werror")
